# This is a basic workflow to help you get started with Actions

name: Main Branch Execution

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Runs a single command using the runners shell
      
      - name: Install necessary npm packages
        run: 
          npm init -y
          npm install
          npm run build --if-present
          npx webdriver-manager update --versions.chrome=86.0.4240.22
          npm install protractor
          npm audit fix --force
        
        if: ${{ always() }}
      - run: npm run apitests
